name: skill_tube
description: "A high-performance, distraction-free learning application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_getit: ^3.0.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.2.0
  internet_connection_checker_plus: ^2.9.1+2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mx_youtube_player:
    path: package/mx_youtube_player
  objectbox: ^4.0.3
  objectbox_flutter: ^4.0.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  talker: ^5.1.13
  talker_bloc_logger: ^4.1.0
  talker_flutter: ^5.1.13
  toastification: ^2.1.0
  uuid: ^4.4.0

dev_dependencies:
  bloc_test: ^9.1.7

  # Code Generation
  build_runner: ^2.4.11
  faker: ^2.1.0
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  # Testing
  mocktail: ^1.0.3
  objectbox_generator: ^4.0.3

  # Tools
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
