name: skill_tube
description: "A high-performance, distraction-free learning application."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_getit: ^3.0.1
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^17.1.0
  internet_connection_checker_plus: ^2.9.1+2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  objectbox: ^5.2.0
  objectbox_flutter_libs: ^5.2.0
  youtube_explode_dart: ^3.0.5
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  talker: ^5.1.13
  talker_bloc_logger: ^5.1.13
  talker_flutter: ^5.1.13
  toastification: ^3.0.3
  uuid: ^4.4.0
  omni_video_player: ^3.7.2
  google_fonts: ^8.0.1

dev_dependencies:

  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  objectbox_generator: ^5.2.0

flutter:
  uses-material-design: true
