name: mx_youtube_player
description: A customized Flutter YouTube player with MX Player-style gestures and UI.
version: 1.0.0
repository: https://github.com/sarbagyastha/youtube_player_flutter
homepage: https://github.com/sarbagyastha/youtube_player_flutter/tree/main/packages/youtube_player_iframe

environment:
  sdk: ^3.10.4
  

dependencies:
  flutter:
    sdk: flutter
  meta: '>=1.7.0 <2.0.0'
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.9.0
  webview_flutter_wkwebview: ^3.23.0
  url_launcher: ^6.3.2
  youtube_player_iframe: ^5.2.2
  youtube_player_iframe_web: ^3.1.2
  # Gestures dependencies
  flutter_volume_controller: ^1.3.4
  screen_brightness: 2.1.7
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/player.html

  plugin:
    platforms:
      web:
        default_package: youtube_player_iframe_web

platforms:
  android:
  ios:
  macos:
  web:

screenshots:
  - description: Youtube Player iFrame Logo
    path: screenshots/logo.png

topics:
  - youtube
  - video
  - player
  - iframe
  - multimedia
  - gestures
  - mx-player
